"""Fixed a bug on Task model

Revision ID: 32894c59eea3
Revises: 946b66baab02
Create Date: 2021-11-26 12:24:10.849741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32894c59eea3'
down_revision = '946b66baab02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
