"""Added name to User

Revision ID: 946b66baab02
Revises: ae0f3dee5948
Create Date: 2021-11-26 12:07:25.781007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946b66baab02'
down_revision = 'ae0f3dee5948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
